services:
  - type: web
    name: bhubaneswar-pathfinding-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: 2.0.0
      - key: FRONTEND_URL
        value: https://bhubaneswar-advanced-pathfinding.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://bhubaneswar-advanced-pathfinding.vercel.app,http://localhost:3000
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
